
//LOCALHOST - VALIDATION


// LOCALHOST

///OWNERS
### GET all owners
GET http://localhost:8080/owners/

### GET owner by ID
GET http://localhost:8080/owners/650c5812c06bc031e32200a1

### CREATE New owner
POST http://localhost:8080/owners HTTP/1.1
Content-Type: application/json

{
    "firstName": "Aaron",
    "lastName": "Erbe",
    "email": "aaronerbe@test.com",
    "password": "Password1!"
}

### UPDATE Existing User
PUT http://localhost:8080/owners/667ed324bf82f7d4f778e75a HTTP/1.1
Content-Type: application/json

{
    "firstName": "A-Aron",
    "lastName": "MyLastName",
    "email": "a-aron@test.com",
    "password": "myPassword1!"
}

### DELETE Existing User
DELETE http://localhost:8080/owners/667ed324bf82f7d4f778e75a HTTP/1.1




///////////////////////////BOATS
### GET all boats
GET http://localhost:8080/boats/

### GET boat by ID
GET http://localhost:8080/boats/650c5812c06bc031e32200b1

### CREATE New boat
POST http://localhost:8080/boats HTTP/1.1
Content-Type: application/json

{
    "ownerId": "650c5812c06bc031e32200a1",
    "name": "Sailing Boat",
    "type": "Sailboat",
    "description": "A nice sailing boat for rent.",
    "location": "Marina Bay",
    "pricePerDay": 150,
    "features": ["GPS", "Life Jackets", "Anchor"],
    "amenities": ["Kitchen", "Bathroom"]
}

### UPDATE Existing boat
PUT http://localhost:8080/boats/667ed3f99e6a8c4e72c5ac2c HTTP/1.1
Content-Type: application/json

{
    "ownerId": "650c5812c06bc031e32200a1",
    "name": "Leapard Catamaran",
    "type": "Sailboat",
    "description": "A nice catamaran sailing boat for rent.",
    "location": "Marina Bay",
    "pricePerDay": 1850,
    "features": ["GPS", "Life Jackets", "Anchor", "Generator"],
    "amenities": ["Kitchen", "Bathroom"]
}

### DELETE Existing boat
DELETE http://localhost:8080/boats/667ed3f99e6a8c4e72c5ac2c HTTP/1.1



///////////ERROR HANDLING
//////////BOATS
### CREATE Bad User ID
POST http://localhost:8080/boats HTTP/1.1
Content-Type: application/json

{
    "ownerId": "667e24a65200e4c3adb9e268",
    "name": "Sailing Boat",
    "type": "Sailboat",
    "description": "A nice sailing boat for rent.",
    "location": "Marina Bay",
    "pricePerDay": 150,
    "features": ["GPS", "Life Jackets", "Anchor"],
    "amenities": ["Kitchen", "Bathroom"]
}

### UPDATE Bad User ID
PUT http://localhost:8080/boats/650c5812c06bc031e32200b1 HTTP/1.1
Content-Type: application/json

{
    "ownerId": "667e24a65200e4c3adb9e268",
    "name": "Leapard Catamaran",
    "type": "Sailboat",
    "description": "A nice catamaran sailing boat for rent.",
    "location": "Marina Bay",
    "pricePerDay": 1850,
    "features": ["GPS", "Life Jackets", "Anchor", "Generator"],
    "amenities": ["Kitchen", "Bathroom"]
}

### GET boat by BAD BOAT ID
GET http://localhost:8080/boats/667e24a65200e4c3adb9e268

### UPDATE BAD boat ID
PUT http://localhost:8080/boats/667e24a65200e4c3adb9e268 HTTP/1.1
Content-Type: application/json

{
    "ownerId": "650c5812c06bc031e32200a1",
    "name": "Leapard Catamaran",
    "type": "Sailboat",
    "description": "A nice catamaran sailing boat for rent.",
    "location": "Marina Bay",
    "pricePerDay": 1850,
    "features": ["GPS", "Life Jackets", "Anchor", "Generator"],
    "amenities": ["Kitchen", "Bathroom"]
}

### DELETE bad Boat ID
DELETE http://localhost:8080/boats/667e24a65200e4c3adb9e268 HTTP/1.1

///////////OWNERS
### GET owner by ID
GET http://localhost:8080/owners/650c5812c06bc031e32200b1

### UPDATE Existing User
PUT http://localhost:8080/owners/650c5812c06bc031e32200b1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "A-Aron",
    "lastName": "MyLastName",
    "email": "a-aron@test.com",
    "password": "myPassword1!"
}